apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoworkflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec: 
  project: default 
  source:
    repoURL: https://github.com/argoproj/argo-workflows/blob/master/manifests/quick-start-postgres.yaml
    targetRevision: HEAD
    # path: blob/master/manifests/
    # include: 'quick-start-postgres.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
