apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argowf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec: 
  project: default 
  source:
    repoURL: https://github.com/derwin4o/argo.git
    targetRevision: HEAD
    path: apps/argowf-install
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
