---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: crossplane
 namespace: crossplane
spec:
 destination:
   namespace: crossplane
   server: https://kubernetes.default.svc
 project: default
 source:
   helm:
#     parameters:
#      - name: build.enabled
#         value: "false"
#       - name: deploy.route.tls.enabled
#         value: "true"
#      - name: image.name
#         value: quay.io/ablock/gitops-helm-quarkus
   chart: crossplane-stable
   repoURL: https://charts.crossplane.io/stable
#   targetRevision: 0.0.3
 syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
   - CreateNamespace=true
